name: google_places_flutter_api
description: Google places autocomplete customizable widget for flutter. Dart 3 compatible.
version: 1.0.2
repository: https://github.com/dev-juju/google_places_flutter_api
homepage: https://github.com/dev-juju/google_places_flutter_api

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_maps_webservices: ^1.0.0
  google_api_headers: ^2.0.0
  http: ^1.0.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  assets:
    - packages/google_places_flutter_api/assets/google_black.png
    - packages/google_places_flutter_api/assets/google_white.png
